version: '3.9'
services:
  mysql:
    image: container-registry.oracle.com/mysql/community-server:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: learning
      MYSQL_USER: application
      MYSQL_PASSWORD: password
