spring:
  application:
    name: learning-service
  datasource:
    url: jdbc:mysql://localhost:3306/learning
    username: application
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8080
